export const UrlAddPost = "http://localhost:8080/api/home/add"
export const UrlGetPosts = "http://localhost:8080/api/home/get/"
export const UrlDelPost = "http://localhost:8080/api/home/del/"
export const UrlEditPost = "http://localhost:8080/api/home/edit/"
export const UrlLogin = "http://localhost:8080/api/login"
export const UrlReg = "http://localhost:8080/api/reg"